blank_issues_enabled: false
contact_links:
  - name: 'Request a Template'
    url: 'https://github.com/yourusername/yourrepository/issues/new?template=template-request.yml'
    about: 'Suggest a new template for create-tgen'
